"""UI composition root (final_plan_verified.md Phase 0 + 1 + 2 + 3 + 4).

Phase 0: wires the existing engine factory + Controller together for
the live GUI session -- no rendering, no game loop.
Phase 1: adds a static-render composition helper (`build_board_view`)
on top of that, using the placeholder assets generated by
`kungfu_chess.scripts.generate_placeholder_assets`.
Phase 2: adds `run_loop`, a real-time loop that measures actual wall-
clock elapsed time each tick and drives `engine.advance_clock` with it.
Phase 3: wires mouse input through -- click a piece, click a
destination, watch it settle.
Phase 4: pieces now glide/hop/breathe instead of popping into place.
`PieceRenderer` takes its own `clock` (defaults to wall-clock, same as
`run_loop`'s) purely to drive sprite animation timing -- independent of
`engine.advance_clock`'s simulation timing, so a headless test can
inject a fake clock into either or both without needing a display.
"""
from __future__ import annotations

import os
import time
from typing import Callable, Tuple

from kungfu_chess.app import build_game_engine
from kungfu_chess.config import GameConfig
from kungfu_chess.engine.game_engine import GameEngine
from kungfu_chess.input.controller import Controller
from kungfu_chess.ui.setup import standard_start_rows
from kungfu_chess.ui.rendering.board_renderer import BoardRenderer
from kungfu_chess.ui.rendering.piece_renderer import PieceRenderer
from kungfu_chess.ui.rendering.overlay_renderer import OverlayRenderer, InputState
from kungfu_chess.ui.rendering.board_view import BoardView
from kungfu_chess.ui.rendering.renderer import Renderer
from kungfu_chess.ui.input.mouse_router import MouseRouter

ASSET_ROOT = os.path.join(os.path.dirname(__file__), "sprites", "assets",
                           "placeholder")
BOARD_BACKGROUND_PATH = os.path.join(ASSET_ROOT, "board.png")


def build_session(config: GameConfig = None) -> Tuple[GameEngine, Controller]:
    """Boots one GameEngine + one Controller for the session, mirroring
    ClickCommand's one-per-engine caching (plan Phase 0 step 3). Reuses
    the already-existing `build_game_engine` factory rather than
    rebuilding engine wiring here."""
    config = config or GameConfig()
    engine = build_game_engine(standard_start_rows, config)
    controller = Controller(engine, config.cell_pixel_size)
    return engine, controller


def build_board_view(config: GameConfig = None,
                      clock: Callable[[], float] = time.perf_counter) -> BoardView:
    """`BoardView` as a thin coordinator over `BoardRenderer` (Phase 1
    background), `PieceRenderer` (Phase 1 compositing, Phase 4
    interpolation + sprite animation), and `OverlayRenderer` (Phase 3
    selection highlight + debug markers). `OverlayRenderer.draw` no-ops
    whenever `input_state` is None, so this same board view still works
    unchanged for a Phase 1/2-style call site that never passes one."""
    config = config or GameConfig()
    board_renderer = BoardRenderer(BOARD_BACKGROUND_PATH)
    piece_renderer = PieceRenderer(ASSET_ROOT, config.cell_pixel_size, clock=clock)
    overlay_renderer = OverlayRenderer(config.cell_pixel_size)
    return BoardView(board_renderer, piece_renderer, overlay_renderer)


def run_loop(engine: GameEngine, controller: Controller, board_view: BoardView,
             renderer: Renderer, clock: Callable[[], float] = time.perf_counter) -> None:
    """Phase 2's real-time loop, extended in Phase 3 with mouse input.
    Each tick: measure actual elapsed wall-clock time -> advance the
    engine's clock by it (settling any due motions) -> build this
    tick's `InputState` from `controller.selected` (the only live
    selection source, plan section 0.4 -- never `snapshot.selected`)
    and the `MouseRouter`'s last-known cursor/click position -> render
    -> display -> poll for quit/close.

    The mouse handler is registered once, before the loop starts, via
    `Renderer.register_mouse_handler` -- a headless test double simply
    leaves that a no-op and can drive `MouseRouter.on_mouse_event`
    directly instead."""
    mouse_router = MouseRouter(controller)
    renderer.register_mouse_handler(mouse_router.on_mouse_event)

    last = clock()
    running = True
    try:
        while running:
            now = clock()
            dt_ms = max(0, int((now - last) * 1000))
            last = now

            engine.advance_clock(dt_ms)
            input_state = InputState(
                selected=controller.selected,
                cursor_pos=mouse_router.cursor_pos,
                last_click_pos=mouse_router.last_click_pos,
            )
            frame = board_view.render(engine.snapshot(), input_state)
            renderer.draw_frame(frame)
            running = renderer.poll_events()
    finally:
        renderer.close()


def main() -> None:  # pragma: no cover
    from kungfu_chess.ui.rendering.cv2_renderer import Cv2Renderer

    config = GameConfig()
    engine, controller = build_session(config)
    board_view = build_board_view(config)
    renderer = Cv2Renderer()
    run_loop(engine, controller, board_view, renderer)


if __name__ == '__main__':  # pragma: no cover
    main()
