"""UI composition root (final_plan_verified.md Phase 0 + 1 + 2 + 3 + 4 + 5,
plus the task-16/17/18 reference-mockup redesign).

Phase 0: wires the existing engine factory + Controller together for
the live GUI session -- no rendering, no game loop.
Phase 1: adds a static-render composition helper (`build_board_view`)
on top of that, using the placeholder assets generated by
`kungfu_chess.scripts.generate_placeholder_assets`.
Phase 2: adds `run_loop`, a real-time loop that measures actual wall-
clock elapsed time each tick and drives `engine.advance_clock` with it.
Phase 3: wires mouse input through -- click a piece, click a
destination, watch it settle.
Phase 4: pieces glide/hop/breathe instead of popping into place.
Phase 5: live side panel (player names/score/recent moves), driven by
the Observer hook from plan section 4A. `wire_event_observers` below is
the ONE place in the whole `ui/` package allowed to import an
engine-internal type (`SettlementEvent`, which carries live `Piece`
values) -- it translates each one into the UI's own plain-value
`MoveResolvedEvent` immediately, before anything reaches `EventBus` or
the observers. Every other UI module (`events.py`, `event_bus.py`,
`moves_log_observer.py`, `score_observer.py`, `panel_renderer.py`)
only ever sees plain strings/ints.

Redesign (matching the reference mockup): the board no longer sits at
screen origin -- a Black panel (left) and White panel (right) flank it,
and a centered "Name: X" / "Score: N" band sits above (Black) and below
(White) it. All the screen-space geometry for that lives here as one
set of constants, and gets threaded through every collaborator that
needs to know where the board now sits on screen: `BoardRenderer`
(paints the checkerboard at the right offset), `PieceRenderer` /
`OverlayRenderer` (draw pieces/selection at the right offset), and
`MouseRouter` (subtracts the offset back out before handing raw screen
clicks to `Controller`, which stays board-space-only and unmodified).
"""
from __future__ import annotations

import os
import time
from typing import Callable, List, Optional, Tuple

from kungfu_chess.app import build_game_engine
from kungfu_chess.config import GameConfig
from kungfu_chess.engine.game_engine import GameEngine
from kungfu_chess.input.controller import Controller
from kungfu_chess.ui.img import Img
from kungfu_chess.ui.setup import standard_start_rows
from kungfu_chess.ui.rendering.board_renderer import BoardRenderer
from kungfu_chess.ui.rendering.piece_renderer import PieceRenderer
from kungfu_chess.ui.rendering.overlay_renderer import OverlayRenderer, InputState
from kungfu_chess.ui.rendering.panel_renderer import PanelRenderer, PanelState
from kungfu_chess.ui.rendering.toast_renderer import ToastRenderer
from kungfu_chess.ui.rendering.board_view import BoardView
from kungfu_chess.ui.rendering.renderer import Renderer
from kungfu_chess.ui.input.mouse_router import MouseRouter
from kungfu_chess.ui.events.event_bus import EventBus
from kungfu_chess.ui.events.events import MoveResolvedEvent
from kungfu_chess.ui.events.observers.moves_log_observer import MoveLogObserver
from kungfu_chess.ui.events.observers.score_observer import ScoreObserver

ASSET_ROOT = os.path.join(os.path.dirname(__file__), "sprites", "assets",
                           "placeholder")
BOARD_BACKGROUND_PATH = os.path.join(ASSET_ROOT, "board.png")

BOARD_COLS = 8
BOARD_ROWS = 8

LEFT_PANEL_WIDTH_PX = 190
RIGHT_PANEL_WIDTH_PX = 190

# Target overall window height in px. The top/bottom name+score bands
# split whatever's left over after the board image's own height, so
# the *total* window height comes out to exactly this value regardless
# of how tall `board.png` itself turns out to be (see `_Layout`'s own
# note on measuring the board image rather than assuming a fixed size).
TARGET_TOTAL_HEIGHT_PX = 900
MIN_BAND_HEIGHT_PX = 20


def build_session(config: GameConfig = None) -> Tuple[GameEngine, Controller]:
    """Boots one GameEngine + one Controller for the session, mirroring
    ClickCommand's one-per-engine caching (plan Phase 0 step 3). Reuses
    the already-existing `build_game_engine` factory rather than
    rebuilding engine wiring here."""
    config = config or GameConfig()
    engine = build_game_engine(standard_start_rows, config)
    controller = Controller(engine, config.cell_pixel_size)
    return engine, controller


def wire_event_observers(engine: GameEngine) -> Tuple[MoveLogObserver, ScoreObserver]:
    """Plan section 4A: bridges GameEngine's settlement-listener hook
    into the UI's own event vocabulary. See module docstring -- this
    function is the sole place a `SettlementEvent` (engine-internal,
    carries live `Piece` values) is ever touched by UI code; everything
    it hands off downstream (`MoveResolvedEvent`) is a plain-value DTO."""
    from kungfu_chess.realtime.motion import SettlementEvent  # composition-root-only bridge import

    event_bus = EventBus()
    move_log = MoveLogObserver(clock_ms_source=lambda: engine.clock_ms)
    score = ScoreObserver()
    event_bus.subscribe_move_resolved(move_log.on_move_resolved)
    event_bus.subscribe_move_resolved(score.on_move_resolved)

    def on_settlement(event: SettlementEvent) -> None:
        event_bus.publish_move_resolved(MoveResolvedEvent(
            piece_color=event.piece.color,
            piece_kind=event.piece.kind,
            src_row=event.src[0], src_col=event.src[1],
            dst_row=event.dst[0], dst_col=event.dst[1],
            captured_piece_kind=event.captured_piece.kind if event.captured_piece else None,
        ))

    engine.add_settlement_listener(on_settlement)
    return move_log, score


class _Layout:
    """Screen-space geometry for the reference-mockup layout, computed
    once from `GameConfig`/board dimensions and shared by every
    collaborator in `build_board_view`/`run_loop` that needs it. Kept as
    a tiny plain-value holder (not itself a renderer) so it can be
    passed around and inspected independently of any `Img`/`cv2` state.

    The checkerboard's own file/rank coordinate-label margin (baked
    into `board.png` by `generate_placeholder_assets.generate_board`)
    is measured directly from the saved image here, rather than trusted
    against a hardcoded constant duplicated between the two modules.
    Bug this fixes: a stale/older `board.png` on disk (e.g. generated
    before that margin existed, or with a different margin) used to
    silently misalign every piece from the grid by however much the
    hardcoded constant and the actual image disagreed -- pieces would
    render offset from the square they're logically on, since
    `piece_offset` was computed from the wrong assumed margin. Reading
    the real image's width/height and comparing it against the known
    raw board size (`cell_pixel_size * cols/rows`) is self-correcting:
    whatever margin the image actually has, on-screen piece placement
    follows it exactly. The top/bottom band heights are likewise derived
    (not hardcoded): `TARGET_TOTAL_HEIGHT_PX` minus the measured board
    image height, split evenly, so the window is exactly
    `TARGET_TOTAL_HEIGHT_PX` tall no matter what size `board.png` is."""

    def __init__(self, config: GameConfig, board_background_path: str):
        self.board_w = config.cell_pixel_size * BOARD_COLS
        self.board_h = config.cell_pixel_size * BOARD_ROWS

        checkerboard = Img().read(board_background_path)
        board_image_w, board_image_h = checkerboard.width, checkerboard.height
        margin_x = max(0, (board_image_w - self.board_w) // 2)
        margin_y = max(0, (board_image_h - self.board_h) // 2)

        leftover = TARGET_TOTAL_HEIGHT_PX - board_image_h
        top_band_height = max(MIN_BAND_HEIGHT_PX, leftover // 2)
        bottom_band_height = max(MIN_BAND_HEIGHT_PX, leftover - top_band_height)
        self.top_band_height = top_band_height
        self.bottom_band_height = bottom_band_height

        self.board_offset_x = LEFT_PANEL_WIDTH_PX
        self.board_offset_y = top_band_height

        # Where the checkerboard's own (0, 0) cell actually starts on
        # screen -- the measured margin further in than the board
        # *image's* top-left corner.
        self.piece_offset = (self.board_offset_x + margin_x,
                              self.board_offset_y + margin_y)

        self.total_width = LEFT_PANEL_WIDTH_PX + board_image_w + RIGHT_PANEL_WIDTH_PX
        self.total_height = top_band_height + board_image_h + bottom_band_height

        self.right_panel_x0 = self.board_offset_x + board_image_w
        self.bottom_band_y0 = self.board_offset_y + board_image_h
        self.board_image_w = board_image_w
        self.board_image_h = board_image_h


def build_board_view(config: GameConfig = None,
                      clock: Callable[[], float] = time.perf_counter) -> Tuple[BoardView, _Layout]:
    """`BoardView` as a thin coordinator over `BoardRenderer` (Phase 1
    background, now widened for the dual side-panel + top/bottom-band
    layout), `PieceRenderer` (Phase 1 compositing, Phase 4 interpolation
    + sprite animation, task 16 screen offset), `OverlayRenderer`
    (Phase 3 selection highlight, task 16 screen offset), `PanelRenderer`
    (Phase 5 player names/score/move log, task 16 dual-panel + centered
    name/score band rework), and `ToastRenderer` (bounce-in "Game Over"
    message, reads `game_over` straight off the snapshot). All four
    optional collaborators no-op whenever their respective state
    argument is None (`ToastRenderer` just reads `snapshot.game_over`
    directly, so it has no separate state argument to gate on).

    Returns `(board_view, layout)` -- callers (`run_loop`, `main`) need
    `layout` too, to size the renderer window and to build `MouseRouter`
    with the matching offset/bounds."""
    config = config or GameConfig()
    layout = _Layout(config, BOARD_BACKGROUND_PATH)

    board_renderer = BoardRenderer(BOARD_BACKGROUND_PATH,
                                    board_offset_x=layout.board_offset_x,
                                    board_offset_y=layout.board_offset_y,
                                    total_width=layout.total_width,
                                    total_height=layout.total_height)
    piece_renderer = PieceRenderer(ASSET_ROOT, config.cell_pixel_size, clock=clock,
                                    offset=layout.piece_offset)
    overlay_renderer = OverlayRenderer(config.cell_pixel_size, offset=layout.piece_offset)
    panel_renderer = PanelRenderer(
        left_panel_x0=0, left_panel_width=LEFT_PANEL_WIDTH_PX,
        right_panel_x0=layout.right_panel_x0, right_panel_width=RIGHT_PANEL_WIDTH_PX,
        panel_height=layout.total_height,
        board_x0=layout.board_offset_x, board_width=layout.board_image_w,
        top_band_y0=0, top_band_height=layout.top_band_height,
        bottom_band_y0=layout.bottom_band_y0, bottom_band_height=layout.bottom_band_height,
    )
    toast_renderer = ToastRenderer(
        center_x=layout.board_offset_x + layout.board_image_w // 2,
        center_y=layout.board_offset_y + layout.board_image_h // 2,
        clock=clock,
    )
    board_view = BoardView(board_renderer, piece_renderer, overlay_renderer,
                            panel_renderer, toast_renderer)
    return board_view, layout


def run_loop(engine: GameEngine, controller: Controller, board_view: BoardView,
             renderer: Renderer, layout: _Layout,
             move_log: Optional[MoveLogObserver] = None,
             score: Optional[ScoreObserver] = None,
             player_names: Tuple[str, str] = ("White", "Black"),
             clock: Callable[[], float] = time.perf_counter) -> None:
    """Phase 2's real-time loop, extended in Phase 3 with mouse input
    and in Phase 5 with a live side panel. Each tick: measure actual
    elapsed wall-clock time -> advance the engine's clock by it
    (settling any due motions, which fires any registered settlement
    listeners synchronously) -> build this tick's `InputState` (from
    `controller.selected`, plan section 0.4) and `PanelState` (from
    `move_log`/`score`, if provided) -> render -> display -> poll for
    quit/close.

    `move_log`/`score` are optional so this loop still works unchanged
    for a caller that hasn't wired Phase 5's observers at all -- the
    panel step in `BoardView.render` simply gets `panel_state=None` and
    skips itself."""
    mouse_router = MouseRouter(controller, board_offset=layout.piece_offset,
                                board_size=(layout.board_w, layout.board_h))
    renderer.register_mouse_handler(mouse_router.on_mouse_event)

    last = clock()
    running = True
    try:
        while running:
            now = clock()
            dt_ms = max(0, int((now - last) * 1000))
            last = now

            engine.advance_clock(dt_ms)
            input_state = InputState(
                selected=controller.selected,
                cursor_pos=mouse_router.cursor_pos,
                last_click_pos=mouse_router.last_click_pos,
            )
            panel_state = None
            if move_log is not None or score is not None:
                white_moves = move_log.recent("w", 8) if move_log is not None else []
                black_moves = move_log.recent("b", 8) if move_log is not None else []
                panel_state = PanelState(
                    white_name=player_names[0],
                    black_name=player_names[1],
                    white_score=score.score["w"] if score is not None else 0,
                    black_score=score.score["b"] if score is not None else 0,
                    white_moves=white_moves,
                    black_moves=black_moves,
                )
            frame = board_view.render(engine.snapshot(), input_state, panel_state)
            renderer.draw_frame(frame)
            running = renderer.poll_events()
    finally:
        renderer.close()


def main() -> None:  # pragma: no cover
    from kungfu_chess.ui.rendering.cv2_renderer import Cv2Renderer

    config = GameConfig()
    engine, controller = build_session(config)
    board_view, layout = build_board_view(config)
    move_log, score = wire_event_observers(engine)
    renderer = Cv2Renderer()
    run_loop(engine, controller, board_view, renderer, layout,
             move_log=move_log, score=score)


if __name__ == '__main__':  # pragma: no cover
    main()
