"""UI composition root (final_plan_verified.md Phase 0 + 1 + 2 + 3 + 4 + 5,
plus the task-16/17/18 reference-mockup redesign).

Phase 0: wires the existing engine factory + Controller together for
the live GUI session -- no rendering, no game loop.
Phase 1: adds a static-render composition helper (`build_board_view`)
on top of that, using the placeholder assets generated by
`kungfu_chess.scripts.generate_placeholder_assets`.
Phase 2: adds `run_loop`, a real-time loop that measures actual wall-
clock elapsed time each tick and drives `engine.advance_clock` with it.
Phase 3: wires mouse input through -- click a piece, click a
destination, watch it settle.
Phase 4: pieces glide/hop/breathe instead of popping into place.
Phase 5: live side panel (player names/score/recent moves), driven by
the Observer hook from plan section 4A. `wire_event_observers` below is
the ONE place in the whole `ui/` package allowed to import an
engine-internal type (`SettlementEvent`, which carries live `Piece`
values) -- it translates each one into the UI's own plain-value
`MoveResolvedEvent` immediately, before anything reaches `EventBus` or
the observers. Every other UI module (`events.py`, `event_bus.py`,
`moves_log_observer.py`, `score_observer.py`, `panel_renderer.py`)
only ever sees plain strings/ints.

Redesign (matching the reference mockup): the board no longer sits at
screen origin -- a Black panel (left) and White panel (right) flank it,
and a centered "Name: X" / "Score: N" band sits above (Black) and below
(White) it. All the screen-space geometry for that lives here as one
set of constants, and gets threaded through every collaborator that
needs to know where the board now sits on screen: `BoardRenderer`
(paints the checkerboard at the right offset), `PieceRenderer` /
`OverlayRenderer` (draw pieces/selection at the right offset), and
`MouseRouter` (subtracts the offset back out before handing raw screen
clicks to `Controller`, which stays board-space-only and unmodified).
"""
from __future__ import annotations

import os
import time
from typing import Callable, List, Optional, Tuple

from kungfu_chess.app import build_game_engine
from kungfu_chess.config import GameConfig
from kungfu_chess.engine.game_engine import GameEngine
from kungfu_chess.input.controller import Controller
from kungfu_chess.ui.setup import standard_start_rows
from kungfu_chess.ui.rendering.board_renderer import BoardRenderer, COORD_MARGIN_PX
from kungfu_chess.ui.rendering.piece_renderer import PieceRenderer
from kungfu_chess.ui.rendering.overlay_renderer import OverlayRenderer, InputState
from kungfu_chess.ui.rendering.panel_renderer import PanelRenderer, PanelState
from kungfu_chess.ui.rendering.toast_renderer import ToastRenderer
from kungfu_chess.ui.rendering.board_view import BoardView
from kungfu_chess.ui.rendering.renderer import Renderer
from kungfu_chess.ui.input.mouse_router import MouseRouter
from kungfu_chess.ui.events.event_bus import EventBus
from kungfu_chess.ui.events.events import JumpResolvedEvent, MoveResolvedEvent
from kungfu_chess.ui.events.observers.moves_log_observer import MoveLogObserver
from kungfu_chess.ui.events.observers.score_observer import ScoreObserver

_SPRITES_DIR = os.path.join(os.path.dirname(__file__), "sprites", "assets")
_REAL_ASSET_ROOT = os.path.join(_SPRITES_DIR, "assets")
_PLACEHOLDER_ASSET_ROOT = os.path.join(_SPRITES_DIR, "placeholder")

# Real (hand-authored/downloaded) piece art, if someone's dropped it
# into `.../sprites/assets/assets/pieces_mine/`, wins over the
# generated placeholder pack automatically -- no setting to flip.
# `SpriteLibrary` does its own, independent version of this same
# detection for loading piece frames; this just decides which folder
# `board.png` also comes from, since the two travel together.
ASSET_ROOT = (_REAL_ASSET_ROOT
              if os.path.isdir(os.path.join(_REAL_ASSET_ROOT, "pieces_mine"))
              else _PLACEHOLDER_ASSET_ROOT)
BOARD_BACKGROUND_PATH = os.path.join(ASSET_ROOT, "board.png")

BOARD_COLS = 8
BOARD_ROWS = 8

LEFT_PANEL_WIDTH_PX = 190
RIGHT_PANEL_WIDTH_PX = 190

# Target overall window height in px. The top/bottom name+score bands
# split whatever's left over after the board image's own height
# (`BOARD_ROWS * cell_pixel_size + 2 * COORD_MARGIN_PX`, always exactly
# that now that `BoardRenderer` draws the margin itself rather than
# relying on it being baked into whatever board.png happens to be on
# disk), so the *total* window height comes out to exactly this value.
TARGET_TOTAL_HEIGHT_PX = 900
MIN_BAND_HEIGHT_PX = 20

# Game-over-toast winner feature: single source of truth for the
# player-name default, shared by `build_board_view` (wires it into
# `ToastRenderer`) and `run_loop` (already used it for `PanelState`) so
# the two can never drift apart from each other.
DEFAULT_PLAYER_NAMES: Tuple[str, str] = ("White", "Black")


def build_session(config: GameConfig = None) -> Tuple[GameEngine, Controller]:
    """Boots one GameEngine + one Controller for the session, mirroring
    ClickCommand's one-per-engine caching (plan Phase 0 step 3). Reuses
    the already-existing `build_game_engine` factory rather than
    rebuilding engine wiring here."""
    config = config or GameConfig()
    engine = build_game_engine(standard_start_rows, config)
    controller = Controller(engine, config.cell_pixel_size)
    return engine, controller


def wire_event_observers(
    engine: GameEngine,
    piece_renderer: Optional[PieceRenderer] = None,
) -> Tuple[MoveLogObserver, ScoreObserver]:
    """Plan section 4A: bridges GameEngine's settlement-listener hook
    into the UI's own event vocabulary. See module docstring -- this
    function is the sole place a `SettlementEvent` (engine-internal,
    carries live `Piece` values) is ever touched by UI code; everything
    it hands off downstream (`MoveResolvedEvent`) is a plain-value DTO.

    `piece_renderer` (new: animation snap-back feature) is optional and
    additive -- passing `None` (the old call shape) behaves exactly as
    before. When given, it's subscribed to `MoveResolvedEvent` the same
    way `move_log`/`score` already are, purely so it can tell a
    truncated landing apart from a normal one (see
    `PieceRenderer.on_move_resolved`) and animate a smooth slide-back
    instead of snapping. This keeps `BoardView` itself a clean
    coordinator with zero knowledge of events -- only this composition
    root wires the renderer to the event bus, exactly like every other
    observer here."""
    from kungfu_chess.realtime.motion import SettlementEvent  # composition-root-only bridge import

    event_bus = EventBus()
    move_log = MoveLogObserver(clock_ms_source=lambda: engine.clock_ms)
    score = ScoreObserver()
    event_bus.subscribe_move_resolved(move_log.on_move_resolved)
    event_bus.subscribe_move_resolved(score.on_move_resolved)
    if piece_renderer is not None:
        event_bus.subscribe_move_resolved(piece_renderer.on_move_resolved)
    # Requirement 3 / hover: jump landings now produce a SettlementEvent
    # (previously they never did -- see SettlementEvent.move_type's
    # docstring). JumpResolvedEvent/on_jump_resolved were already
    # declared for exactly this; this is the first time anything
    # actually publishes one.
    event_bus.subscribe_jump_resolved(score.on_jump_resolved)

    def on_settlement(event: SettlementEvent) -> None:
        if event.move_type == 'jump':
            event_bus.publish_jump_resolved(JumpResolvedEvent(
                piece_color=event.piece.color,
                piece_kind=event.piece.kind,
                row=event.dst[0], col=event.dst[1],
                captured_piece_kind=event.captured_piece.kind if event.captured_piece else None,
            ))
            return

        event_bus.publish_move_resolved(MoveResolvedEvent(
            piece_color=event.piece.color,
            piece_kind=event.piece.kind,
            src_row=event.src[0], src_col=event.src[1],
            dst_row=event.dst[0], dst_col=event.dst[1],
            captured_piece_kind=event.captured_piece.kind if event.captured_piece else None,
            requested_dst_row=event.requested_dst[0] if event.requested_dst else None,
            requested_dst_col=event.requested_dst[1] if event.requested_dst else None,
        ))

    engine.add_settlement_listener(on_settlement)
    return move_log, score


class _Layout:
    """Screen-space geometry for the reference-mockup layout, computed
    once from `GameConfig`/board dimensions and shared by every
    collaborator in `build_board_view`/`run_loop` that needs it. Kept as
    a tiny plain-value holder (not itself a renderer) so it can be
    passed around and inspected independently of any `Img`/`cv2` state.

    `BoardRenderer` owns drawing the file/rank coordinate-label margin
    (`COORD_MARGIN_PX`) around whatever checkerboard image it's given
    -- always exactly that many pixels, regardless of the raw board
    image's own native size (placeholder-generated or a real external
    asset), since it stretch-fits that image to `cell_pixel_size *
    cols/rows` first. So the resulting labeled-board image size is pure
    arithmetic here, nothing needs to be read off disk to compute it."""

    def __init__(self, config: GameConfig):
        self.board_w = config.cell_pixel_size * BOARD_COLS
        self.board_h = config.cell_pixel_size * BOARD_ROWS
        board_image_w = self.board_w + 2 * COORD_MARGIN_PX
        board_image_h = self.board_h + 2 * COORD_MARGIN_PX

        leftover = TARGET_TOTAL_HEIGHT_PX - board_image_h
        top_band_height = max(MIN_BAND_HEIGHT_PX, leftover // 2)
        bottom_band_height = max(MIN_BAND_HEIGHT_PX, leftover - top_band_height)
        self.top_band_height = top_band_height
        self.bottom_band_height = bottom_band_height

        self.board_offset_x = LEFT_PANEL_WIDTH_PX
        self.board_offset_y = top_band_height

        # Where the checkerboard's own (0, 0) cell actually starts on
        # screen -- always exactly COORD_MARGIN_PX further in than the
        # board *image's* top-left corner (see class docstring).
        self.piece_offset = (self.board_offset_x + COORD_MARGIN_PX,
                              self.board_offset_y + COORD_MARGIN_PX)

        self.total_width = LEFT_PANEL_WIDTH_PX + board_image_w + RIGHT_PANEL_WIDTH_PX
        self.total_height = top_band_height + board_image_h + bottom_band_height

        self.right_panel_x0 = self.board_offset_x + board_image_w
        self.bottom_band_y0 = self.board_offset_y + board_image_h
        self.board_image_w = board_image_w
        self.board_image_h = board_image_h


def build_board_view(config: GameConfig = None,
                      clock: Callable[[], float] = time.perf_counter,
                      player_names: Tuple[str, str] = DEFAULT_PLAYER_NAMES
                      ) -> Tuple[BoardView, _Layout]:
    """`BoardView` as a thin coordinator over `BoardRenderer` (Phase 1
    background, now widened for the dual side-panel + top/bottom-band
    layout), `PieceRenderer` (Phase 1 compositing, Phase 4 interpolation
    + sprite animation, task 16 screen offset), `OverlayRenderer`
    (Phase 3 selection highlight, task 16 screen offset), `PanelRenderer`
    (Phase 5 player names/score/move log, task 16 dual-panel + centered
    name/score band rework), and `ToastRenderer` (bounce-in "Game Over"
    message, reads `game_over` straight off the snapshot). All four
    optional collaborators no-op whenever their respective state
    argument is None (`ToastRenderer` just reads `snapshot.game_over`
    directly, so it has no separate state argument to gate on).

    Returns `(board_view, layout)` -- callers (`run_loop`, `main`) need
    `layout` too, to size the renderer window and to build `MouseRouter`
    with the matching offset/bounds."""
    config = config or GameConfig()
    layout = _Layout(config)

    board_renderer = BoardRenderer(BOARD_BACKGROUND_PATH,
                                    cell_pixel_size=config.cell_pixel_size,
                                    cols=BOARD_COLS, rows=BOARD_ROWS,
                                    board_offset_x=layout.board_offset_x,
                                    board_offset_y=layout.board_offset_y,
                                    total_width=layout.total_width,
                                    total_height=layout.total_height)
    piece_renderer = PieceRenderer(ASSET_ROOT, config.cell_pixel_size, clock=clock,
                                    offset=layout.piece_offset)
    overlay_renderer = OverlayRenderer(config.cell_pixel_size, offset=layout.piece_offset,
                                        clock=clock)
    panel_renderer = PanelRenderer(
        left_panel_x0=0, left_panel_width=LEFT_PANEL_WIDTH_PX,
        right_panel_x0=layout.right_panel_x0, right_panel_width=RIGHT_PANEL_WIDTH_PX,
        panel_height=layout.total_height,
        board_x0=layout.board_offset_x, board_width=layout.board_image_w,
        top_band_y0=0, top_band_height=layout.top_band_height,
        bottom_band_y0=layout.bottom_band_y0, bottom_band_height=layout.bottom_band_height,
    )
    toast_renderer = ToastRenderer(
        center_x=layout.board_offset_x + layout.board_image_w // 2,
        center_y=layout.board_offset_y + layout.board_image_h // 2,
        clock=clock,
        player_names=player_names,
    )
    board_view = BoardView(board_renderer, piece_renderer, overlay_renderer,
                            panel_renderer, toast_renderer)
    return board_view, layout


def run_loop(engine: GameEngine, controller: Controller, board_view: BoardView,
             renderer: Renderer, layout: _Layout,
             move_log: Optional[MoveLogObserver] = None,
             score: Optional[ScoreObserver] = None,
             player_names: Tuple[str, str] = DEFAULT_PLAYER_NAMES,
             clock: Callable[[], float] = time.perf_counter) -> None:
    """Phase 2's real-time loop, extended in Phase 3 with mouse input
    and in Phase 5 with a live side panel. Each tick: measure actual
    elapsed wall-clock time -> advance the engine's clock by it
    (settling any due motions, which fires any registered settlement
    listeners synchronously) -> build this tick's `InputState` (from
    `controller.selected`, plan section 0.4) and `PanelState` (from
    `move_log`/`score`, if provided) -> render -> display -> poll for
    quit/close.

    `move_log`/`score` are optional so this loop still works unchanged
    for a caller that hasn't wired Phase 5's observers at all -- the
    panel step in `BoardView.render` simply gets `panel_state=None` and
    skips itself."""
    mouse_router = MouseRouter(controller, board_offset=layout.piece_offset,
                                board_size=(layout.board_w, layout.board_h))
    renderer.register_mouse_handler(mouse_router.on_mouse_event)

    last = clock()
    running = True
    try:
        while running:
            now = clock()
            dt_ms = max(0, int((now - last) * 1000))
            last = now

            engine.advance_clock(dt_ms)
            # Movement-range highlight feature: recomputed fresh every
            # tick straight from the engine, same as `selected` below is
            # rebuilt fresh from the Controller -- never cached/stale,
            # and never bypasses GameEngine's own legality gates.
            selected = controller.selected
            legal_destinations = (
                engine.legal_destinations(selected) if selected is not None else ()
            )
            input_state = InputState(
                selected=selected,
                cursor_pos=mouse_router.cursor_pos,
                last_click_pos=mouse_router.last_click_pos,
                legal_destinations=legal_destinations,
            )
            panel_state = None
            if move_log is not None or score is not None:
                white_moves = move_log.recent("w", 8) if move_log is not None else []
                black_moves = move_log.recent("b", 8) if move_log is not None else []
                panel_state = PanelState(
                    white_name=player_names[0],
                    black_name=player_names[1],
                    white_score=score.score["w"] if score is not None else 0,
                    black_score=score.score["b"] if score is not None else 0,
                    white_moves=white_moves,
                    black_moves=black_moves,
                )
            frame = board_view.render(engine.snapshot(), input_state, panel_state)
            renderer.draw_frame(frame)
            running = renderer.poll_events()
    finally:
        renderer.close()


def main() -> None:  # pragma: no cover
    from kungfu_chess.ui.rendering.cv2_renderer import Cv2Renderer

    config = GameConfig()
    engine, controller = build_session(config)
    board_view, layout = build_board_view(config)
    move_log, score = wire_event_observers(engine, board_view.piece_renderer)
    renderer = Cv2Renderer()
    run_loop(engine, controller, board_view, renderer, layout,
             move_log=move_log, score=score)


if __name__ == '__main__':  # pragma: no cover
    main()
